### ISSUE TITLE
Double url in entries

### ISSUE THREAD

**Issue by JohnGeorge** [ckatzorke/howlongtobeat#1]
When using search, response returns imageUrl that exposes duplicate url.  
E.g. https://howlongtobeat.com/https://howlongtobeat.com/gameimages/36936_Nioh.jpg

**Comment by ckatzorke** [comment]
Thank you @JohnGeorge. fixed. 
Release will follow

**Comment by ckatzorke** [comment]
1.0.8 released (1.0.7 was faulty)
https://www.npmjs.com/package/howlongtobeat
