### ISSUE TITLE
Empty imageUrl and playableOn

### ISSUE THREAD

**Issue by kharator** [ckatzorke/howlongtobeat#15]
When getting a game by its id, the imageUrl field is undefined and the playableOn array is empty. 

For the imageUrl i don't understand why it's not working.
For the playableOn it seems that the scrapper is getting the wrong path in the dom.

**Comment by ckatzorke** [comment]
Do you have an example for the imageUrl? I added a test for detail() and I am receiving a proper imageurl...
Regarding the "playableOn": On howlongtobeat.com, it has been replaced by "Platforms:". I changed the code, and also introduced a new property "platforms", but also kept "playableOn" for backward compatibility

**Comment by kharator** [comment]
It seems that the imageUrl issue is not reproducible anymore. 
Thanks for the "platforms" addition, i can't wait to be able to get this new property in my results.

**Comment by ckatzorke** [comment]
Cool, hope it works. Keep in mind, it will only work when getting the details, not when searching.
Closing this issue, have fun!
