### ISSUE TITLE
Call Limit?

### ISSUE THREAD

**Issue by maysaleba** [ckatzorke/howlongtobeat#32]
Hi,

big fan of this api. Just want to know if there is a call limit, can i use it to say query 1000 titles every 2 hours?

**Comment by ckatzorke** [comment]
Hi, this is not really an API, it is just a scraping wrapper around the outstanding website / service https://howlongtobeat.com/.
I am not aware of any limit, but I would assume that it would not be well received if you scrape 1000 titles every 2 hours - and they may block you.
Cheers
Christian
