### ISSUE TITLE
The Endpoint changed

### ISSUE THREAD

**Issue by ScrappyCocco** [ckatzorke/howlongtobeat#36]
Hello, it's me again, I used your api as inspiration to create https://github.com/ScrappyCocco/HowLongToBeat-PythonAPI

As you can read from https://github.com/ScrappyCocco/HowLongToBeat-PythonAPI/issues/10 the endpoint changed so the old requests seem to no longer work. I was not able to understand what changed yet because I always get a 404 trying with the new URL

I'll investigate next week as soon as I have the time, but if you want to have a look please let me know if you find something

Thank you

**Comment by ScrappyCocco** [comment]
I fixed the Python Library with this commit if it may help you

https://github.com/ScrappyCocco/HowLongToBeat-PythonAPI/commit/f2f87754aa09807a818973f623858f500d589731

or open the issue linked above to read more

**Comment by maysaleba** [comment]
Hoping this gets fixed here soon
