### ISSUE TITLE
Fix api for HowLongToBeat

### ISSUE THREAD

**Issue by ScrappyCocco** [ckatzorke/howlongtobeat#6]
Hello, i used your api to create [https://github.com/ScrappyCocco/HowLongToBeat-PythonAPI](https://github.com/ScrappyCocco/HowLongToBeat-PythonAPI) a month ago or so.

HowLongToBeat changed the search page, so i just wanted to tell you to fix your line as i did [here (link to commit)](https://github.com/ScrappyCocco/HowLongToBeat-PythonAPI/commit/1a2e4f437f9059d41b5e5148173ed29229f0ff9f#diff-c817b588ee6d8aca58a59a7b9b3ab341).

Let me know if it works for you too
Thank you

**Comment by ckatzorke** [comment]
Great! Many thanks for the advice. 
Fixed in [this commit](https://github.com/ckatzorke/howlongtobeat/commit/34b9799edbf65d2e035d7e155cd0f1351693e28a)

**Comment by ScrappyCocco** [comment]
You're welcome
Just a quick tip: fix your travis badge in the readme, clicking it should open the build, i think you copied the wrong link
Bye ^^
